/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

import com.alee.laf.WebLookAndFeel;
import java.awt.BorderLayout;
import java.awt.Frame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author ACER
 */
public class MainActivity extends javax.swing.JFrame {

    /**
     * Creates new form MainActivity
     */
    public MainActivity() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelUtama = new javax.swing.JPanel();
        rSPanelGradiente2 = new rspanelgradiente.RSPanelGradiente();
        rSPanelGradiente1 = new rspanelgradiente.RSPanelGradiente();
        jMenuBar1 = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        miDataObat = new javax.swing.JMenuItem();
        miApoteker = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Apoteker");

        PanelUtama.setLayout(new java.awt.BorderLayout());
        getContentPane().add(PanelUtama, java.awt.BorderLayout.CENTER);

        rSPanelGradiente2.setColorPrimario(new java.awt.Color(0, 204, 204));
        rSPanelGradiente2.setColorSecundario(new java.awt.Color(51, 0, 204));

        javax.swing.GroupLayout rSPanelGradiente2Layout = new javax.swing.GroupLayout(rSPanelGradiente2);
        rSPanelGradiente2.setLayout(rSPanelGradiente2Layout);
        rSPanelGradiente2Layout.setHorizontalGroup(
            rSPanelGradiente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        rSPanelGradiente2Layout.setVerticalGroup(
            rSPanelGradiente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        getContentPane().add(rSPanelGradiente2, java.awt.BorderLayout.PAGE_START);

        rSPanelGradiente1.setColorPrimario(new java.awt.Color(0, 204, 204));
        rSPanelGradiente1.setColorSecundario(new java.awt.Color(51, 0, 204));

        javax.swing.GroupLayout rSPanelGradiente1Layout = new javax.swing.GroupLayout(rSPanelGradiente1);
        rSPanelGradiente1.setLayout(rSPanelGradiente1Layout);
        rSPanelGradiente1Layout.setHorizontalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        rSPanelGradiente1Layout.setVerticalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        getContentPane().add(rSPanelGradiente1, java.awt.BorderLayout.PAGE_END);

        mFile.setText("File");

        miDataObat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        miDataObat.setText("Data Obat");
        miDataObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDataObatActionPerformed(evt);
            }
        });
        mFile.add(miDataObat);

        miApoteker.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        miApoteker.setText("Data Apoterker");
        mFile.add(miApoteker);
        mFile.add(jSeparator1);

        miLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        miLogout.setText("Logout");
        miLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogoutActionPerformed(evt);
            }
        });
        mFile.add(miLogout);

        jMenuBar1.add(mFile);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miDataObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDataObatActionPerformed
        // TODO add your handling code here:
        TambahComponent(new DataObat());
    }//GEN-LAST:event_miDataObatActionPerformed

    private void miLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogoutActionPerformed
        // TODO add your handling code here:
        int logout = JOptionPane.showConfirmDialog(this, "EXIT Applications ?","Komfirmasi",JOptionPane.YES_NO_OPTION);
        if (logout == JOptionPane.YES_NO_OPTION) {
            dispose();
            this.setVisible(false);
            this.setDefaultCloseOperation(EXIT_ON_CLOSE);
            System.exit(0);
        } else {
        }
    }//GEN-LAST:event_miLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        try {
            UIManager.setLookAndFeel(new WebLookAndFeel());
        } catch (Exception e) {
        }
        
        java.awt.EventQueue.invokeLater(() -> {
//            new MainActivity().setVisible(true);
            MainActivity L = new MainActivity();
            L.setExtendedState(Frame.MAXIMIZED_BOTH);
            L.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JPanel PanelUtama;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenuItem miApoteker;
    private javax.swing.JMenuItem miDataObat;
    private javax.swing.JMenuItem miLogout;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente1;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente2;
    // End of variables declaration//GEN-END:variables

    public static void TambahComponent(JPanel panel) {
        if (PanelUtama.getComponentCount() > 0) {
            PanelUtama.removeAll();
        }
        PanelUtama.add(panel, BorderLayout.CENTER);
        PanelUtama.revalidate();
        PanelUtama.repaint();
    }


}
