/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class TambahObat extends javax.swing.JPanel {

    /**
     * Creates new form TambahDokter
     */
    public TambahObat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        rSPanelGradiente1 = new rspanelgradiente.RSPanelGradiente();
        jLabel2 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtjmlh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtdesc = new javax.swing.JTextArea();
        btnSimpan = new keeptoo.KButton();

        setBackground(new java.awt.Color(0, 153, 204));
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        rSPanelGradiente1.setColorPrimario(new java.awt.Color(0, 204, 204));
        rSPanelGradiente1.setColorSecundario(new java.awt.Color(51, 0, 204));
        rSPanelGradiente1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama Obat");
        rSPanelGradiente1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 26));
        rSPanelGradiente1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 310, 30));

        txtjmlh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtjmlhKeyTyped(evt);
            }
        });
        rSPanelGradiente1.add(txtjmlh, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 310, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jumlah Obat");
        rSPanelGradiente1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 26));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Deskripsi");
        rSPanelGradiente1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 26));

        txtdesc.setColumns(20);
        txtdesc.setRows(5);
        rSPanelGradiente1.add(txtdesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 310, 110));

        btnSimpan.setBackground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.setkBorderRadius(45);
        btnSimpan.setkEndColor(new java.awt.Color(51, 0, 204));
        btnSimpan.setkHoverEndColor(new java.awt.Color(0, 204, 204));
        btnSimpan.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnSimpan.setkHoverStartColor(new java.awt.Color(51, 0, 204));
        btnSimpan.setkSelectedColor(new java.awt.Color(0, 255, 255));
        btnSimpan.setkStartColor(new java.awt.Color(0, 204, 204));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        rSPanelGradiente1.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, 40));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 69;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 30, 11, 32);
        add(rSPanelGradiente1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
                String nama = txtNama.getText();
        String jmlh = txtjmlh.getText();
        String desc = txtdesc.getText();
        if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama Harus diisi");
            txtdesc.requestFocus();
        }else{
            try {
                Connection c = Koneksi.MySQl();
                Statement st = c.createStatement();
                String query = "INSERT INTO tb_obat (nama_obat,jumlah_obat,deskripsi) VALUES ('"+nama+"','"+jmlh+"','"+desc+"')";
                st.executeUpdate(query);
                JOptionPane.showMessageDialog(this, "Data telah disimpan");
                MainActivity.TambahComponent(new DataObat());
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }

        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtjmlhKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjmlhKeyTyped
        // TODO add your handling code here:
        char Angka = evt.getKeyChar();
        if(!Character.isDigit(Angka)){
            evt.consume();
        }
        if ( txtjmlh.getText().length() == 3 ) {
        evt.consume(); 
    }
    }//GEN-LAST:event_txtjmlhKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente1;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextArea txtdesc;
    private javax.swing.JTextField txtjmlh;
    // End of variables declaration//GEN-END:variables
}
