/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class UbahObat extends javax.swing.JPanel {
    
    Resource obat;
    /**
     * Creates new form TambahDokter
     */
    public UbahObat(Resource d) {
        initComponents();
        
        obat = d;
        txtNama.setText(obat.getNama_obat());
        txtjmlh.setText(obat.getJumlah_obat());
        jTextArea1.setText(obat.getDeskripsi());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        rSPanelGradiente1 = new rspanelgradiente.RSPanelGradiente();
        jLabel2 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtjmlh = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnUbah = new keeptoo.KButton();

        setBackground(new java.awt.Color(0, 153, 204));
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        rSPanelGradiente1.setColorPrimario(new java.awt.Color(0, 204, 204));
        rSPanelGradiente1.setColorSecundario(new java.awt.Color(51, 0, 204));
        rSPanelGradiente1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama Obat");
        rSPanelGradiente1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, 26));
        rSPanelGradiente1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 310, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jumlah Obat");
        rSPanelGradiente1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, 26));

        txtjmlh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtjmlhKeyTyped(evt);
            }
        });
        rSPanelGradiente1.add(txtjmlh, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 310, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Deskripsi");
        rSPanelGradiente1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, 26));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        rSPanelGradiente1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 310, -1));

        btnUbah.setBackground(new java.awt.Color(255, 255, 255));
        btnUbah.setText("Ubah");
        btnUbah.setkBorderRadius(45);
        btnUbah.setkEndColor(new java.awt.Color(51, 0, 204));
        btnUbah.setkHoverEndColor(new java.awt.Color(0, 204, 204));
        btnUbah.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnUbah.setkHoverStartColor(new java.awt.Color(51, 0, 204));
        btnUbah.setkSelectedColor(new java.awt.Color(0, 255, 255));
        btnUbah.setkStartColor(new java.awt.Color(0, 204, 204));
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        rSPanelGradiente1.add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, 40));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 65;
        gridBagConstraints.ipady = 64;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 28, 17, 50);
        add(rSPanelGradiente1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        String nama = txtNama.getText();
        String jmlh = txtjmlh.getText();
        String desc = jTextArea1.getText();
        if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(btnUbah, nama);
            txtNama.requestFocus();
        }else{
            try {
                Connection c = Koneksi.MySQl();
                Statement st = c.createStatement();
                String query = "UPDATE tb_obat SET nama_obat='"+nama+"',jumlah_obat='"+jmlh+"',deskripsi='"+desc+"' WHERE id_obat="+obat.getId()+"";
                st.executeUpdate(query);
                JOptionPane.showMessageDialog(this, "Data telah diubah!");
                MainActivity.TambahComponent(new DataObat());
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }

        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void txtjmlhKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjmlhKeyTyped
        // TODO add your handling code here:
        char Angka = evt.getKeyChar();
        if(!Character.isDigit(Angka)){
            evt.consume();
        }
        if ( txtjmlh.getText().length() == 3 ) {
        evt.consume(); 
    }
    }//GEN-LAST:event_txtjmlhKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente1;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtjmlh;
    // End of variables declaration//GEN-END:variables
}
